export const ARTWORKS = [
  { id: '1',  title: 'Manton De',                       artist: 'Magnus',        medium: 'Installation — hide & fringe',     price: 'Price on Request', color: 0xc8a050 },
  { id: '2a', title: 'Summer 1',                        artist: 'Casey',         medium: 'Mixed media on paper',             price: '$300',             color: 0xd4c8b0 },
  { id: '2b', title: 'Summer 100',                      artist: 'Casey',         medium: 'Mixed media on paper',             price: '$300',             color: 0xc8d0b8 },
  { id: '2c', title: 'Raft 3',                          artist: 'Casey',         medium: 'Mixed media',                      price: '$3000',            color: 0xe8d8c0 },
  { id: '3a', title: 'Untitled',                        artist: 'Rohen Jones',   medium: 'Oil on canvas',                    price: '$800',             color: 0x8a4030 },
  { id: '3b', title: "People I Don't Know (monster)",   artist: 'Rohen Jones',   medium: 'Mixed media on canvas',            price: 'Price on Request', color: 0x141810 },
  { id: '3c', title: 'Man Pushing Thru / Shower',       artist: 'Rohen Jones',   medium: 'Oil on canvas',                    price: '$800',             color: 0xb0a870 },
  { id: '3d', title: 'Raft 3',                          artist: 'Casey',         medium: 'Mixed media',                      price: '$3000',            color: 0xe0d0a8 },
  { id: '4',  title: 'Dear Glove',                      artist: 'Faye',          medium: 'Found objects / installation',     price: '$450',             color: 0xe8e8e8 },
  { id: '5a', title: 'Suspended Cloud',                 artist: 'Jonah',         medium: 'Mixed media installation',         price: '$6000',            color: 0xd8e0c8 },
  { id: '5b', title: 'Untitled',                        artist: 'Jonah',         medium: 'Oil on canvas',                    price: '$350',             color: 0x384838 },
  { id: '6a', title: 'Dragonfly Touches Water',         artist: 'Winnie',        medium: 'Mixed media on paper',             price: 'Price on Request', color: 0xb8c8d8 },
  { id: '6b', title: 'Of Time',                         artist: 'Winnie',        medium: 'Ink wash on paper',                price: 'Price on Request', color: 0x606060 },
  { id: '7a', title: 'Helium',                          artist: 'Timothy Zhang', medium: 'Oil on canvas',                    price: 'Price on Request', color: 0x3a4030 },
  { id: '7b', title: 'Ghost of Fear',                   artist: 'Timothy Zhang', medium: 'Oil on canvas',                    price: 'Price on Request', color: 0x304828 },
  { id: '7c', title: 'Untitled',                        artist: 'Timothy Zhang', medium: 'Mixed media on canvas',            price: 'Price on Request', color: 0x5a3828 },
  { id: '7d', title: 'The Joke',                        artist: 'Timothy Zhang', medium: 'Oil on canvas',                    price: 'Price on Request', color: 0xc03020 },
  { id: '8',  title: 'PARADE!',                         artist: 'Isaac Ball',    medium: 'Ink on paper — wall installation', price: '$2500 per piece',  color: 0xd8d0c0 },
]

// Real image paths — place files in /public/artworks/
export const ARTWORK_IMAGE_URLS = {
  '1':  '/artworks/magnus-manton-de.png',
  '3a': '/artworks/rohen-jones-untitled.png',
  '3b': '/artworks/rohen-jones-people-i-dont-know.png',
  '3c': '/artworks/rohen-jones-man-pushing-thru-shower.png',
  '4':  '/artworks/faye-dear-glove.png',
  '5a': '/artworks/jonah-suspended-cloud.png',
  '5b': '/artworks/jonah-untitled.png',
  '6a': '/artworks/winne-dragonfly-touches-water.png',
  '6b': '/artworks/winne-of-time.png',
  '7a': '/artworks/timothy-zhang-helium.png',
  '7b': '/artworks/timothy-zhang-ghost-of-fear.png',
  '7c': '/artworks/timothy-zhang-untitled.png',
  '7d': '/artworks/timothy-zhang-the-joke.png',
  '8':  '/artworks/isaac-ball-parade.png',
}
