import type { Artwork } from '../../engine/types'

export const TROJAN_HORSE_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Manton De',
    artist: 'Magnus',
    medium: 'Installation — hide & fringe',
    price: 'Price on Request',
    color: 0xc8a050,
    imageUrl: '/exhibitions/trojan-horse/artworks/magnus-manton-de.png',
    fit: 'contain',
  },
  {
    id: '2a',
    title: 'Summer 1',
    artist: 'Casey',
    medium: 'Mixed media on paper',
    price: '$300',
    color: 0xd4c8b0,
    imageUrl: '/exhibitions/trojan-horse/artworks/casey.png',
  },
  {
    id: '2b',
    title: 'Summer 100',
    artist: 'Casey',
    medium: 'Mixed media on paper',
    price: '$300',
    color: 0xc8d0b8,
    imageUrl: '/exhibitions/trojan-horse/artworks/casey.png',
  },
  {
    id: '2c',
    title: 'Raft 3',
    artist: 'Casey',
    medium: 'Mixed media',
    price: '$3000',
    color: 0xe8d8c0,
    imageUrl: '/exhibitions/trojan-horse/artworks/casey.png',
  },
  {
    id: '3a',
    title: 'Untitled',
    artist: 'Rohen Jones',
    medium: 'Oil on canvas',
    price: '$800',
    color: 0x8a4030,
    imageUrl: '/exhibitions/trojan-horse/artworks/rohen-jones-untitled.png',
  },
  {
    id: '3b',
    title: "People I Don't Know (monster)",
    artist: 'Rohen Jones',
    medium: 'Mixed media on canvas',
    price: 'Price on Request',
    color: 0x141810,
    imageUrl: '/exhibitions/trojan-horse/artworks/rohen-jones-people-i-dont-know.png',
  },
  {
    id: '3c',
    title: 'Man Pushing Thru / Shower',
    artist: 'Rohen Jones',
    medium: 'Oil on canvas',
    price: '$800',
    color: 0xb0a870,
    imageUrl: '/exhibitions/trojan-horse/artworks/rohen-jones-man-pushing-thru-shower.png',
  },
  {
    id: '3d',
    title: 'Raft 3',
    artist: 'Casey',
    medium: 'Mixed media',
    price: '$3000',
    color: 0xe0d0a8,
    imageUrl: '/exhibitions/trojan-horse/artworks/casey.png',
  },
  {
    id: '4',
    title: 'Dear Glove',
    artist: 'Faye',
    medium: 'Found objects / installation',
    price: '$450',
    color: 0xe8e8e8,
    imageUrl: '/exhibitions/trojan-horse/artworks/faye-dear-glove.png',
  },
  {
    id: '5a',
    title: 'Suspended Cloud',
    artist: 'Jonah',
    medium: 'Mixed media installation',
    price: '$6000',
    color: 0xd8e0c8,
    imageUrl: '/exhibitions/trojan-horse/artworks/jonah-suspended-cloud.png',
  },
  {
    id: '5b',
    title: 'Untitled',
    artist: 'Jonah',
    medium: 'Oil on canvas',
    price: '$350',
    color: 0x384838,
    imageUrl: '/exhibitions/trojan-horse/artworks/jonah-untitled.png',
  },
  {
    id: '6a',
    title: 'Dragonfly Touches Water',
    artist: 'Winnie',
    medium: 'Mixed media on paper',
    price: 'Price on Request',
    color: 0xb8c8d8,
    imageUrl: '/exhibitions/trojan-horse/artworks/winne-dragonfly-touches-water.png',
  },
  {
    id: '6b',
    title: 'Of Time',
    artist: 'Winnie',
    medium: 'Ink wash on paper',
    price: 'Price on Request',
    color: 0x606060,
    imageUrl: '/exhibitions/trojan-horse/artworks/winne-of-time.png',
  },
  {
    id: '7a',
    title: 'Helium',
    artist: 'Timothy Zhang',
    medium: 'Oil on canvas',
    price: 'Price on Request',
    color: 0x3a4030,
    imageUrl: '/exhibitions/trojan-horse/artworks/timothy-zhang-helium.png',
  },
  {
    id: '7b',
    title: 'Ghost of Fear',
    artist: 'Timothy Zhang',
    medium: 'Oil on canvas',
    price: 'Price on Request',
    color: 0x304828,
    imageUrl: '/exhibitions/trojan-horse/artworks/timothy-zhang-ghost-of-fear.png',
  },
  {
    id: '7c',
    title: 'Untitled',
    artist: 'Timothy Zhang',
    medium: 'Mixed media on canvas',
    price: 'Price on Request',
    color: 0x5a3828,
    imageUrl: '/exhibitions/trojan-horse/artworks/timothy-zhang-untitled.png',
  },
  {
    id: '7d',
    title: 'The Joke',
    artist: 'Timothy Zhang',
    medium: 'Oil on canvas',
    price: 'Price on Request',
    color: 0xc03020,
    imageUrl: '/exhibitions/trojan-horse/artworks/timothy-zhang-the-joke.png',
  },
  {
    id: '8',
    title: 'PARADE!',
    artist: 'Isaac Ball',
    medium: 'Ink on paper — wall installation',
    price: '$2500 per piece',
    color: 0xd8d0c0,
    imageUrl: '/exhibitions/trojan-horse/artworks/isaac-ball-parade.jpg',
    fit: 'contain',
  },
]
